### ISSUE TITLE
FreeRTOS with LoRaWAN

### ISSUE THREAD

**Issue by rajSilikon** [danak6jq/Seeed-LoRa-E5#10]
Hi.

I have been experiencing issues when enabling FreeRTOS with this code.

Anyone having same issues? or have been able to run FreeRTOS with LoRaWAN for Seeed LoRa-E5 Dev Board?

when I enable FREERTOS, lora_app also gets modified and produces error 

![er1](https://user-images.githubusercontent.com/108116747/175493508-a8793a94-47fe-4aac-80a3-bb97672dfc82.PNG)

"Description	Resource	Path	Location	Type
'CFG_SEQ_Prio_0' undeclared (first use in this function)	lora_app.c line 518	C/C++ Problem
"

Description	Resource	Path	Location	Type
'CFG_SEQ_Task_LoRaSendOnTxTimerOrButtonEvent' undeclared (first use in this function)	lora_app.c line 517	C/C++ Problem

I need to have FREERTOS enabled since I am building a CLASS C device in which there will be a button that can be triggered anytime to display certain info. 

I cant do this on the main loop due to LoRaWAN restrictions (timing issues).

**Comment by danak6jq** [comment]
ST STM32WL firmware provides an example "LoRaWAN_End_Node_FreeRTOS". I suggest looking at the Cube / IOC settings and code in that project to see how they might be added to this project (look at every detail in the IOC file).

Alternatively, and probably best, you may want to 'port' the LoRaWAN_End_Node_FreeRTOS example the same way I ported this example, using this repo as a reference for configuration changes and support code. Still, look at every detail in the IOC file, the defaults will not work.

In either case, this issue is out of the scope of this project.
